apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      service: elasticsearch
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: elasticsearch
    spec:
      containers:
      - image: elasticsearch:latest
        name: elasticsearch
        ports:
        - containerPort: 9200
          protocol: TCP
        - containerPort: 9300
          protocol: TCP
        resources: {}
      restartPolicy: Always
status: {}
