apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: elasticsearch
  name: elasticsearch
spec:
  ports:
  - name: "9200"
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: "9300"
    port: 9300
    protocol: TCP
    targetPort: 9300
  selector:
    service: elasticsearch
status:
  loadBalancer: {}
