apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: logstash
  name: logstash
spec:
  ports:
  - name: "5000"
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    service: logstash
status:
  loadBalancer: {}
