apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: logstash
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      service: logstash
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: logstash
    spec:
      containers:
      - name: logstash
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
      restartPolicy: Always
status: {}
